languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Documenting my Steam Deck Journey"
header.logo = "img/logo.png"
description = "Guides for Handheld Addicts (featuring Steam Deck!)"
copyright = "©{{< year >}} handheld.quest"

dateFormat = "2 January 2006"
